name: custom nginx

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -f Dockerfile -t my-nginx .

      - name: Run the Docker image
        run: docker run -d -p 8080:80 my-nginx

      - name: Check if container is running
        run: docker ps

      - name: Test the application
        run: curl -I http://localhost:8080